### ISSUE TITLE
OneDrive link for the ShanghaiTech Campus dataset is broken.

### ISSUE THREAD

**Issue by figkim** [svip-lab/svip-lab.github.io#3]
Hi there.

I tried to access ShanghaiTech Campus dataset through [your github pages](https://svip-lab.github.io/dataset/campus_dataset.html),
But the OneDrive link shows 404 error.

Also I tried another script [from someone's source](https://github.com/StevenLiuWen/ano_pred_cvpr2018/blob/master/Data/shanghaitech.sh), 
it also returns 404 error.

Could you confirm that the dataset is still valid?
Thanks.

**Comment by hbb1** [comment]
Thank you. We have updated the url. http://download.impersonator.org:8181/dataset/ShanghaiTech/

**Comment by joos2010kj** [comment]
Hello,
I think the link is broken again.

Could you update the link?

**Comment by zachluo** [comment]
> Hello, I think the link is broken again.
> 
> Could you update the link?

http://101.32.75.151:8181/dataset/
@joos2010kj

**Comment by joos2010kj** [comment]
> 

Perfect, thanks!

**Comment by StevenLiuWen** [comment]
Hi, @joos2010kj 


You could also download the ShanghaiTech dataset from the following links (the file is split into 7 sub-filed):

GooleDrive: https://drive.google.com/drive/folders/1n64x4lTLw5LsfmL-Z6VH9IoBu6EDzK1m

or 

OneDrive: https://1drv.ms/u/s!AjjUqiJZsj8whLt-1ABerTT-9eH9Ag?e=eJbY6Y

Step 1: Download all split files (from shanghaitech.tar.gz.aa to shanghaitech.tar.gz.ag)

Step 2: Open a Linux or Mac terminal, and merge all split files by 

```Bash

cat shanghaitech.tar.gz.* > shanghaitech.tar.gz
```

Step 3: Extract the shanghaitech.tar.gz

If you encounter any problems, feel free to contact us.

Best wishes.
